# Generated by Django 3.1.4 on 2021-07-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20, verbose_name='图书名')),
            ],
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(help_text='角色名不能为空', max_length=20, verbose_name='角色名')),
                ('gender', models.CharField(choices=[('0', '男'), ('1', '女')], max_length=1)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('role_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.bookinfo')),
            ],
        ),
    ]
