# Generated by Django 3.1.4 on 2021-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='book_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roleinfo',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='roleinfo',
            name='gender',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
